### ISSUE TITLE
can not build

### ISSUE THREAD

**Issue by nepvibes** [qingxiang-jia/full-cloud-pinyin#11]
there is build error no build target 
![Screenshot_select-area_20231014145523](https://github.com/qingxiang-jia/full-cloud-pinyin/assets/145452727/58ebcca8-7593-4b5c-a868-1fd8f3e0a710)

**Comment by qingxiang-jia** [comment]
Hi, sorry for the delay. Please try the following in the fcp-fcitx5 directory:
`./run init` and then `/.run bir`. See the script content for what it's doing.
