### ISSUE TITLE
Offline usage

### ISSUE THREAD

**Issue by autofool** [qingxiang-jia/full-cloud-pinyin#16]
Google Input Tools was available on windows as separate offline client. Is there any way we can leverage that to use it without internet and integrate with this project?

**Comment by qingxiang-jia** [comment]
Yeah, technically we can. For example, talking to one of those existing input methods. But I plan to keep this project simple. If the user needs offline usage, Fcitx5 already comes with a decent pinyin input method.

Feel free to reopen this issue.
